### ISSUE TITLE
License problems

### ISSUE THREAD

**Issue by sfalkner** [zeyuanxy/niseko#2]
Hello,

thanks for this package and the underlying data. I would like to use this in my research, but can't right now, because the data I have to download does not have a license attached to it. Could you consider adding a permissive license to it?
Additionally, the license file says "IT LICENSE", bit I think it's the standard "MIT LICENSE", right?
Thank you!

**Comment by zeyuanxy** [comment]
@sfalkner Thanks for letting us know! We have fixed the license issue, you are more than welcome to use it in your research!

**Comment by sfalkner** [comment]
That was super fast, thank you! Looking forward to playing around with all data and exploring it.
